declare module "lucide-react" {
  import { FC, SVGProps } from "react"

  type Icon = FC<SVGProps<SVGSVGElement>>
  export type LucideIcon = Icon

  export const Activity: Icon
  export const AlertCircle: Icon
  export const AlertTriangle: Icon
  export const Archive: Icon
  export const ArrowDown: Icon
  export const ArrowLeft: Icon
  export const ArrowRight: Icon
  export const ArrowUp: Icon
  export const ArrowUpRight: Icon
  export const Award: Icon
  export const Badge: Icon
  export const BadgeCheck: Icon
  export const BarChart3: Icon
  export const Bell: Icon
  export const BookOpen: Icon
  export const Brain: Icon
  export const Building2: Icon
  export const Calendar: Icon
  export const Camera: Icon
  export const Check: Icon
  export const CheckCircle: Icon
  export const CheckCircle2: Icon
  export const ChevronDown: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const ChevronUp: Icon
  export const Clipboard: Icon
  export const Clock: Icon
  export const Crown: Icon
  export const Download: Icon
  export const DownloadCloud: Icon
  export const Edit: Icon
  export const ExternalLink: Icon
  export const Eye: Icon
  export const EyeOff: Icon
  export const Facebook: Icon
  export const FileText: Icon
  export const Filter: Icon
  export const Flag: Icon
  export const Gift: Icon
  export const Globe: Icon
  export const GraduationCap: Icon
  export const Handshake: Icon
  export const Heart: Icon
  export const HelpCircle: Icon
  export const Home: Icon
  export const Image: Icon
  export const Info: Icon
  export const Instagram: Icon
  export const LayoutDashboard: Icon
  export const Lightbulb: Icon
  export const Linkedin: Icon
  export const Loader2: Icon
  export const LogIn: Icon
  export const LogOut: Icon
  export const Mail: Icon
  export const MapPin: Icon
  export const Medal: Icon
  export const Megaphone: Icon
  export const Menu: Icon
  export const MessageCircle: Icon
  export const MessageSquare: Icon
  export const Minus: Icon
  export const Moon: Icon
  export const MoreHorizontal: Icon
  export const Newspaper: Icon
  export const Package: Icon
  export const Pencil: Icon
  export const Phone: Icon
  export const Play: Icon
  export const Plus: Icon
  export const Quote: Icon
  export const Receipt: Icon
  export const Rocket: Icon
  export const RotateCcw: Icon
  export const Save: Icon
  export const School: Icon
  export const Search: Icon
  export const SearchCheck: Icon
  export const Send: Icon
  export const Separator: Icon
  export const Settings: Icon
  export const Share2: Icon
  export const Shield: Icon
  export const ShoppingBag: Icon
  export const ShoppingCart: Icon
  export const SlidersHorizontal: Icon
  export const Sparkles: Icon
  export const Star: Icon
  export const Sun: Icon
  export const Tag: Icon
  export const Target: Icon
  export const ThumbsUp: Icon
  export const Trash2: Icon
  export const TrendingDown: Icon
  export const TrendingUp: Icon
  export const Trophy: Icon
  export const Truck: Icon
  export const Twitter: Icon
  export const Upload: Icon
  export const User: Icon
  export const UserCog: Icon
  export const Users: Icon
  export const Video: Icon
  export const X: Icon
  export const Youtube: Icon
  export const Zap: Icon
}
